<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EQLWikiAssistant.Core\EQLWikiAssistant.Core.csproj" />
    <ProjectReference Include="..\EQLWikiAssistant.Wiki\EQLWikiAssistant.Wiki.csproj" />
  </ItemGroup>

</Project>
