<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EQLWikiEditorAssistant.Core\EQLWikiEditorAssistant.Core.csproj" />
    <ProjectReference Include="..\EQLWikiEditorAssistant.Wiki\EQLWikiEditorAssistant.Wiki.csproj" />
  </ItemGroup>

</Project>
